"""add datetime mixin

Revision ID: d43e1b8089ea
Revises: bda05400543e
Create Date: 2024-12-12 01:22:34.708753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43e1b8089ea'
down_revision: Union[str, None] = 'bda05400543e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='creation time'))
    op.add_column('records', sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'))
    op.add_column('roles', sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='creation time'))
    op.add_column('roles', sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'))
    op.add_column('users', sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='creation time'))
    op.add_column('users', sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='update time'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_time')
    op.drop_column('users', 'created_time')
    op.drop_column('roles', 'updated_time')
    op.drop_column('roles', 'created_time')
    op.drop_column('records', 'updated_time')
    op.drop_column('records', 'created_time')
    # ### end Alembic commands ###
