"""remove unused from user

Revision ID: 5f16556e53a2
Revises: 0732047758b1
Create Date: 2024-12-12 05:58:56.481049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f16556e53a2'
down_revision: Union[str, None] = '0732047758b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_constraint('uq_users_uuid', 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_users_uuid', 'users', ['uuid'])
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
