"""init

Revision ID: bda05400543e
Revises:
Create Date: 2024-12-11 18:41:13.426229

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bda05400543e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
        sa.Column('name', sa.String(length=20), nullable=False, comment='role name'),
        sa.Column('is_active', sa.Boolean(), nullable=False, comment='role activation status'),
        sa.Column('remark', sa.TEXT(), nullable=True, comment='remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
        sa.UniqueConstraint('name', name=op.f('uq_roles_name')),
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
        sa.Column('uuid', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(length=20), nullable=False, comment='user name'),
        sa.Column('supervisor_id', sa.Integer(), nullable=True, comment='supervisor id'),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['supervisor_id'], ['users.id'], name=op.f('fk_users_supervisor_id_users'), ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('uuid', name=op.f('uq_users_uuid')),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table(
        'records',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key id'),
        sa.Column('bot_token', sa.String(length=255), nullable=False, comment='bot token'),
        sa.Column('chat_id', sa.String(length=255), nullable=False, comment='chat id'),
        sa.Column('message', sa.String(), nullable=False, comment='message'),
        sa.Column('sent_time', sa.DateTime(), nullable=True, comment='sent time'),
        sa.Column('sent_response', sa.String(), nullable=False, comment='sent status'),
        sa.Column('user_id', sa.Integer(), nullable=True, comment='records user id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_records_user_id_users'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_records')),
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.create_table(
        'user_roles',
        sa.Column('user_id', sa.Integer(), nullable=False, comment='user id'),
        sa.Column('role_id', sa.Integer(), nullable=False, comment='role id'),
        sa.ForeignKeyConstraint(
            ['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
